stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://nifty-thompson-192338.netlify.com/
  only:
    - netlify-test
  script:
    - npm i
    # your build command
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod